version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-review: 
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - run:
          name: Install pyLint and json2html
          command: pip install pylint pylint-json2html
      - run:
          name: Run pyLint
          command: |
            pylint parse_offers --output-format=json:pylint.json,colorized || true
            pylint-json2html -o pylint.html pylint.json
      - run:
          command: |
            mkdir -p /tmp/report_dump
            cp pylint.json /tmp/report_dump
            cp pylint.html /tmp/report_dump
      - store_artifacts:
          path: /tmp/report_dump
workflows:
  code-review: 
    jobs:
      - build-and-review